database:
  mysql:
    main:
      host: localhost
      port: 3306
      user: testuser
      password: testpassword
      database: testdb
      charset: utf8mb4
    root:
      host: localhost
      port: 3306
      user: root
      password: rootpassword
      database: testdb
      charset: utf8mb4
